version: '3'
services:
  grafana:
    image: grafana/grafana-oss:8.5.22
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_ALLOW_LOADING_UNSIGNED_PLUGINS=servicenow-cloudobservability-datasource
      - GF_LOG_LEVEL=debug
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dist:/var/lib/grafana/plugins/servicenow-cloudobservability-datasource
volumes:
  grafana-storage:
